pipeline {
    agent any

    stages {
        stage('SCM checkout') {
            steps {
                     git branch: 'main', credentialsId: 'git_key', url: 'git@github.com:teranteks/vagrant_linux_docker_jenkins_tomcat_nginx.git'
                
            }
        }
        
        stage('Cd In Jenkins WorkSpace') {
          steps{
              script{
                    withCredentials([string(credentialsId: 'jen_workspace', variable: 'workspace')]) {
                        sh 'cd $workspace'
                        sh 'ls -altr'
                    }
              }
          }
        }
        
        stage('ansible') {
          steps{
                sh 'ansible-playbook /var/jenkins_home/workspace/nginx_setup/ansible/setup_nginx.yaml -i /var/jenkins_home/workspace/nginx_setup/ansible/inventory.ini'
          }
        }
    }
}
